# Introduction to PyTorch

In [2]:
import torch

# Basic Operations

In [3]:
torch.rand(2,2) # tensor tamaño 2x2 de valores random [0,1]

tensor([[0.6868, 0.2399],
        [0.5714, 0.5479]])

In [4]:
torch.empty(3,3) # tensor 3x3 de valores vacíos

tensor([[ 0.0000e+00,  4.6566e-10, -2.1782e-24],
        [ 2.8657e-42,  9.8091e-45,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [6]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.zeros(2,3).dtype

torch.float32

In [8]:
torch.zeros(2,3, dtype= torch.double).dtype
#torch.zeros(2,3, dtype= torch.int).dtype

torch.float64

In [10]:
# creamos tensor a partir de lista
torch.tensor([2.5,0.3,12])

tensor([ 2.5000,  0.3000, 12.0000])

In [11]:
x = torch.rand(2,2)
y = torch.rand(2,2)
z = x + y
z

tensor([[1.2612, 1.2342],
        [0.5733, 0.8892]])

In [12]:
z = torch.add(x,y)
z

tensor([[1.2612, 1.2342],
        [0.5733, 0.8892]])

En pytorch, cada función con un `_`, hará un `inplace = True`

In [15]:
y.add_(x)
y

tensor([[1.7974, 2.1797],
        [0.5858, 1.1957]])

In [16]:
torch.mul(x,y)

tensor([[0.9637, 2.0609],
        [0.0073, 0.3665]])

In [18]:
torch.div(x,y)

tensor([[0.2983, 0.4338],
        [0.0214, 0.2563]])

# Autograd

In [34]:
x = torch.rand(3,requires_grad=True)

Utilizando este comando, lo que hacemos es crear un grafo con el que a partir de ahora podremos calcular gradientes.

In [35]:
y = x+2
print(y)

tensor([2.6983, 2.9259, 2.0752], grad_fn=<AddBackward0>)


esto crea un grafo con variables input x y 2 y nos da un ouput que es y, del cual podemos obtener el gradiente $\frac{dy}{dx}$

In [36]:
z = y*y*2
print(z)

tensor([14.5620, 17.1217,  8.6127], grad_fn=<MulBackward0>)


In [37]:
mean = z.mean()
print(mean)

tensor(13.4321, grad_fn=<MeanBackward0>)


In [39]:
mean.backward() # d mean/dx
print(x.grad)

tensor([3.5978, 3.9012, 2.7669])
