# Introduction to PyTorch

In [1]:
import torch

# Basic Operations

In [2]:
torch.rand(2,2) # tensor tamaño 2x2 de valores random [0,1]

tensor([[0.5863, 0.2676],
        [0.9528, 0.0665]])

In [3]:
torch.empty(3,3) # tensor 3x3 de valores vacíos

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [4]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
torch.zeros(2,3).dtype

torch.float32

In [6]:
torch.zeros(2,3, dtype= torch.double).dtype
#torch.zeros(2,3, dtype= torch.int).dtype

torch.float64

In [7]:
# creamos tensor a partir de lista
torch.tensor([2.5,0.3,12])

tensor([ 2.5000,  0.3000, 12.0000])

In [8]:
x = torch.rand(2,2)
y = torch.rand(2,2)
z = x + y
z

tensor([[1.6213, 1.3012],
        [0.8220, 0.6290]])

In [9]:
z = torch.add(x,y)
z

tensor([[1.6213, 1.3012],
        [0.8220, 0.6290]])

En pytorch, cada función con un `_`, hará un `inplace = True`

In [10]:
y.add_(x)
y

tensor([[1.6213, 1.3012],
        [0.8220, 0.6290]])

In [11]:
torch.mul(x,y)

tensor([[1.3557, 0.7273],
        [0.4989, 0.2030]])

In [12]:
torch.div(x,y)

tensor([[0.5157, 0.4296],
        [0.7384, 0.5131]])

# Autograd

In [13]:
x = torch.rand(3,requires_grad=True)

Utilizando este comando, lo que hacemos es crear un grafo con el que a partir de ahora podremos calcular gradientes.

In [14]:
y = x+2
print(y)

tensor([2.2526, 2.2690, 2.3668], grad_fn=<AddBackward0>)


esto crea un grafo con variables input x y 2 y nos da un ouput que es y, del cual podemos obtener el gradiente $\frac{dy}{dx}$

In [15]:
z = y*y*2
print(z)

tensor([10.1485, 10.2966, 11.2039], grad_fn=<MulBackward0>)


In [16]:
mean = z.mean()
print(mean)

tensor(10.5497, grad_fn=<MeanBackward0>)


In [17]:
mean.backward() # d mean/dx
print(x.grad)

tensor([3.0035, 3.0253, 3.1558])
